### PR TITLE
added border and moving image

### PR DESCRIPTION
**Pull request by kritika902**

### CODE REVIEW

**Comment by kritika902** [comment]
hacktober
hackt
the last image is moving

**Comment by kritika902** [comment]
this image which is in circle is moving from left to right

**Comment by rhvsingh** [comment]
> this image which is in circle is moving from left to right

Does it look good? Think like if you are opening this website for the first as a user. Will you like it?

**Comment by kritika902** [comment]
Ok I m removing it

**Comment by kritika902** [comment]
Sir plz merge my pr

**Comment by kritika902** [comment]
Sir plz merge my pr plz sir

**Pull request merged**
