### PR TITLE
Added Hover Button Html File

### PR DESCRIPTION
**Pull request by 23SumiTM**
Added Hover Button Html File And A Hactober 2022 Image

### CODE REVIEW

**Comment by rhvsingh** [comment]
@23SumiTM please attach screenshot of it.

**Comment by 23SumiTM** [comment]
Which Screenshot?

**Comment by rhvsingh** [comment]
> Which Screenshot?

Changes you made

**Comment by 23SumiTM** [comment]
addedchanges

screenshot added

**Comment by 23SumiTM** [comment]
i have added a image also.
Image name Fd_tCCPWYAAt4R-.jpg

**Comment by rhvsingh** [comment]
I meant the changes you made in UI. How do they look? Take a screenshot of that then attach it here.
I can see your commits and the changes you have made in the file but not how they appear for that you have to attach a screenshot. It will be easy for me to understand. I hope you got my point.

For example, see this [PR](https://github.com/Rajkumar-justcoder/Animated-name/pull/7)

**Pull request merged**
